    name: Selection Sort Workflow

    on:
      workflow_dispatch:
      push:
        tags:
          - checkMeSort*

    jobs:
      build:
        name: Autograding Selection Sort
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: curl https://www.cis.gvsu.edu/~kurmasz/Autograder/autogradeNcK.tar.bz2 | tar xvj
          - run: java -jar munit.jar selection_sort.asm SelectionSortTest_Strong.class
